# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{memcache_stat}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["watsonian"]
  s.date = %q{2010-07-25}
  s.description = %q{Ruby library that fetches and wraps memcached stats output.}
  s.email = %q{watsonian@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/memcache_stat.rb",
     "memcache_stat.gemspec",
     "test/helper.rb",
     "test/test_memcache_stat.rb"
  ]
  s.homepage = %q{http://github.com/watsonian/memcache_stat}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby library that fetches and wraps memcached stats output.}
  s.test_files = [
    "test/helper.rb",
     "test/test_memcache_stat.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<memcache_do>, [">= 0.1.1"])
    else
      s.add_dependency(%q<memcache_do>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<memcache_do>, [">= 0.1.1"])
  end
end

